### ISSUE TITLE
Inference single image by using pretrained checkpoints?

### ISSUE THREAD

**Issue by kerberosargos** [RylonW/DocNLC#2]
Hello thank you for your great job.

I have a question. is there any way to inference single image by using pretrained checkpoints?

Thank you in advance for your support.

**Comment by kerberosargos** [comment]
Hello again. I have solved myself. I am sharing codes for  If somebody needs

**predict.py** is new file

```
import os
import cv2
import torch
import numpy as np
import argparse
import pathlib

from utils import util
import options.options as option
from models import create_model

import torch
from PIL import Image
import torchvision.transforms as transforms


def predict(image_str:str):

    image: np.ndarray = cv2.imread(image_str) 

    parser = argparse.ArgumentParser()
    parser.add_argument('--opt', type=str, default='./options/test.yml',
                        help='Path to option YAML file.')
    parser.add_argument('--launcher', choices=['none', 'pytorch'], default='pytorch', help='job launcher')
    parser.add_argument('--local_rank', type=int, default=0)
    args = parser.parse_args()
    opt = option.parse(args.opt, is_train=False)

    opt['dist'] = False
    
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Define a transform to convert
    # the image to torch tensor
    transform = transforms.Compose([
        transforms.ToTensor()
    ])

    # Convert the image to Torch tensor
    tensor_image = transform(image).unsqueeze(0)


    # Model & Metrics
    model = create_model(opt)
    para = {}
    for k,v in torch.load(opt['path']['pretrain_model_G']).items():
        k = 'module.'+k
        para[k] = v
    model.netG.load_state_dict(para, strict=True)

    model.netG.eval()

    output = util.single_forward(model.netG,tensor_image )

    np_image = util.tensor2img(output) 

    np_image = cv2.cvtColor(np_image, cv2.COLOR_RGB2BGR)

    cv2.imshow("Image Preview", np_image)
    cv2.waitKey()

    result_dir = opt['path']['results_root']

    if not os.path.exists(result_dir):
        os.makedirs(result_dir)
    
    image_name = pathlib.Path(image_str).name 

    saved_image_path = f"{result_dir}{image_name}"

    cv2.imwrite(saved_image_path,np_image)

    print(f"{saved_image_path} is saved")
    
    return np_image


if "__main__":

    predict("./input/3540289a59d449e080d5ea93d0538c17-ezsam.png")
```

**./options/test.yml** is modified file

```
#### general settings
name: TEST # logger name
use_tb_logger: true
model: sr # model name. We would load model architectures according to ['model'] param.
distortion: sr
scale: 1
gpu_ids: None

#### datasets
datasets:
  # The training part is not actually used during testing. But I just want to reduce unwanted problems, so I keep it.
  train:
    name: UEN
    mode: UEN_train
    interval_list: [1]
    random_reverse: false
    border_mode: false
    cache_keys: ~
    filelist: ./xxx.txt

    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 12
    # IN_size: 384
    IN_size: 256
    augment: true
    color: RGB

  val:
    name: UEN
    mode: UEN_test
    filelist: ./test.txt # Change it to your path. The image paths used for testing should be stored in this file.
    batch_size: 1 # Do not change
    use_shuffle: false


#### network structures
network_G:
  which_model_G: SID
  nf: 16
  groups: 8

#### path
path:
  root: ./output/
  results_root: ./output/
  pretrain: ./SIEN/pretrain1 # This is not important. Just keep it.
  pretrain_model_G: './pretrain/26_G.pth' # model weight path
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
# The training setting is not actually used during testing. But I just want to reduce unwanted problems, so I keep it.
train:
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  # niter: 1200000
  niter: 1
  ewc: false
  distill: true
  ewc_coff: 50.0
  distill_coff: 0.2
  fix_some_part: ~
  warmup_iter: -1  # -1: no warm up
  ComputeImportance: false
  istraining: true
  lr_scheme: MultiStepLR
  lr_steps: [60, 90]
  lr_gamma: 0.5

  eta_min: !!float 5e-6
  pixel_criterion: l1
  pixel_weight: 5000.0
  ssim_weight: 1000.0
  vgg_weight: 1000.0

  val_epoch: !!float 1
  manual_seed: 0

#### logger
logger:
  print_freq: 40
  save_checkpoint_epoch: !!float 25
```

Thank you again for your effort
